import { StyleSheet } from "@react-pdf/renderer";

export const reportStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#0f172a",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#f59e0b",
    paddingBottom: 12,
  },
  logo: {
    width: 72,
    height: 72,
    objectFit: "contain",
  },
  companyName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#0f172a",
  },
  companyMeta: {
    fontSize: 9,
    color: "#475569",
    marginTop: 4,
    lineHeight: 1.4,
  },
  formTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#0f172a",
    textAlign: "center",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  formSubtitle: {
    fontSize: 9,
    color: "#64748b",
    textAlign: "center",
    marginBottom: 14,
  },
  certBanner: {
    marginBottom: 14,
    padding: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
    textAlign: "center",
  },
  certNumber: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#b45309",
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#b45309",
    marginBottom: 6,
    textTransform: "uppercase",
  },
  block: {
    marginBottom: 16,
  },
  row: {
    flexDirection: "row",
    gap: 16,
  },
  col: {
    flex: 1,
  },
  label: {
    fontSize: 8,
    color: "#64748b",
    textTransform: "uppercase",
    marginBottom: 2,
  },
  value: {
    fontSize: 10,
    lineHeight: 1.4,
  },
  summaryBox: {
    padding: 10,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
  },
  summaryPass: {
    color: "#047857",
    fontWeight: "bold",
    fontSize: 12,
  },
  summaryFail: {
    color: "#b91c1c",
    fontWeight: "bold",
    fontSize: 12,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#1e293b",
    color: "#f8fafc",
    padding: 6,
    fontWeight: "bold",
    fontSize: 9,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    padding: 6,
    fontSize: 9,
  },
  colItem: { width: "46%" },
  nfpaRef: {
    fontSize: 7,
    color: "#64748b",
    marginTop: 2,
    lineHeight: 1.3,
  },
  colResult: { width: "14%" },
  colNotes: { width: "40%" },
  resultPass: { color: "#047857" },
  resultFail: { color: "#b91c1c" },
  resultNa: { color: "#475569" },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  photo: {
    width: "48%",
    height: 140,
    objectFit: "cover",
    borderRadius: 4,
  },
  signature: {
    width: 220,
    height: 80,
    objectFit: "contain",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    marginTop: 4,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#94a3b8",
    textAlign: "center",
  },
});
