import type { Metadata } from "next";
import Link from "next/link";
import { APP_NAME, PILOT_PRICING } from "@/lib/branding";
import { TRIAL_DAYS } from "@/lib/billing/constants";
import { buildPublicPageMetadata } from "@/lib/seo/site-metadata";

const lastUpdated = "June 1, 2026";
const standardPlanPrice = `${PILOT_PRICING.standard.price}${PILOT_PRICING.standard.period}`;

export const metadata: Metadata = buildPublicPageMetadata({
  title: `Terms of Service`,
  description: `Terms of Service for ${APP_NAME}.`,
  path: "/terms",
});

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: [
      `By accessing or using ${APP_NAME}, you agree to these Terms of Service. If you are using the service on behalf of an organization, you represent that you have authority to bind that organization to these terms.`,
    ],
  },
  {
    title: "2. Service Description",
    body: [
      `${APP_NAME} provides software tools for fire inspection companies, including scheduling, customer and building records, field inspection workflows, compliance reports, repair quote workflows, and related operational features.`,
      "The service is not a substitute for professional judgment, licensed inspection work, code interpretation, or legal advice. Your organization remains responsible for inspection accuracy, regulatory compliance, and customer communications.",
    ],
  },
  {
    title: "3. Accounts and Access",
    body: [
      "You are responsible for keeping your account credentials secure and for all activity under your account. You must provide accurate account information and promptly update it when needed.",
      "Administrators and owners are responsible for managing user access, roles, and company data within their organization.",
    ],
  },
  {
    title: "4. Customer and Inspection Data",
    body: [
      "You retain ownership of the customer, building, inspection, photo, signature, report, and quote data that you enter into the service.",
      "You grant us the limited rights needed to host, process, transmit, display, back up, and support that data for operating the service.",
      "You are responsible for ensuring that you have permission to upload and process any personal information, photos, signatures, or business records submitted through the service.",
    ],
  },
  {
    title: "5. Acceptable Use",
    body: [
      "You may not misuse the service, attempt unauthorized access, interfere with service operations, upload malicious code, violate applicable laws, or use the service to infringe the rights of others.",
      "We may suspend or restrict access if we reasonably believe the service is being used in a way that creates security, legal, operational, or abuse risk.",
    ],
  },
  {
    title: "6. Reports, Quotes, and Communications",
    body: [
      "Reports, inspection records, and quotes generated by the service depend on the information entered by your users. You are responsible for reviewing generated materials before relying on or sending them.",
      "If email sending is enabled, you authorize the service to send operational emails, compliance reports, and quote messages to recipients you provide.",
    ],
  },
  {
    title: "7. Availability and Changes",
    body: [
      "We aim to keep the service reliable, but we do not guarantee uninterrupted or error-free operation. Features may change as the product improves.",
      "We may update these terms from time to time. Continued use of the service after updates means you accept the revised terms.",
    ],
  },
  {
    title: "8. Fees and Billing",
    body: [
      `${APP_NAME} offers a ${TRIAL_DAYS}-day free trial for new company workspaces. During the trial you can use the service without charge; trial terms are shown at sign-up and in your dashboard.`,
      `After the trial, continued access requires a paid subscription at ${standardPlanPrice} (USD unless another currency is shown at checkout), billed monthly on a recurring basis unless you cancel.`,
      "Checkout, payment processing, invoicing, tax calculation, and subscription management are provided by Paddle.com, which acts as Merchant of Record for paid orders. By subscribing you also agree to Paddle buyer terms applicable to your purchase.",
      "Subscriptions renew automatically each billing period until cancelled. You may cancel at any time from your billing page or through Paddle; cancellation stops future charges and typically takes effect at the end of the current paid period unless otherwise required by law.",
      "If your trial ends or your subscription lapses, access to paid features may be restricted until you subscribe again.",
      "Pricing, taxes, and any promotional terms are shown before you complete checkout. Refunds and statutory withdrawal rights are described in our Refund Policy at /refund.",
    ],
  },
  {
    title: "9. Limitation of Liability",
    body: [
      "To the maximum extent permitted by law, the service is provided as is and as available. We are not liable for indirect, incidental, special, consequential, or punitive damages, or for lost profits, revenue, data, or business opportunities.",
      "Our total liability for claims related to the service will not exceed the amounts paid for the service during the three months before the event giving rise to the claim.",
    ],
  },
  {
    title: "10. Contact",
    body: [
      "Questions about these terms can be sent to support@getflareflow.com.",
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <section className="mx-auto flex w-full max-w-3xl flex-col gap-8 px-4 py-12 sm:px-6 lg:py-16">
        <div className="space-y-4">
          <Link href="/" className="text-sm text-primary hover:underline">
            Back to {APP_NAME}
          </Link>
          <div className="space-y-3">
            <p className="text-sm font-medium uppercase tracking-wide text-primary">
              {APP_NAME}
            </p>
            <h1 className="font-heading text-3xl font-semibold tracking-tight sm:text-4xl">
              Terms of Service
            </h1>
            <p className="text-sm text-muted-foreground">
              Last updated: {lastUpdated}
            </p>
          </div>
        </div>

        <div className="rounded-xl border border-border bg-card p-5 text-sm leading-6 text-muted-foreground shadow-sm sm:p-6">
          <p>
            These terms are a practical operating agreement for using {APP_NAME}.
            They are not legal advice and may need review by your attorney before
            launch or customer rollout.
          </p>
        </div>

        <div className="space-y-8">
          {sections.map((section) => (
            <section key={section.title} className="space-y-3">
              <h2 className="font-heading text-xl font-semibold tracking-tight">
                {section.title}
              </h2>
              {section.body.map((paragraph) => (
                <p key={paragraph} className="text-sm leading-6 text-muted-foreground">
                  {paragraph}
                </p>
              ))}
            </section>
          ))}
        </div>
      </section>
    </main>
  );
}
