import { rowsToCsv } from "@/lib/export/csv";

export const ASSET_IMPORT_TEMPLATE_HEADERS = [
  "branch",
  "customer",
  "building_name",
  "address_line1",
  "city",
  "postal_code",
  "asset_type",
  "location",
  "tag_number",
  "barcode",
  "manufacturer",
  "model",
  "serial_number",
  "last_service_at",
  "next_service_due",
  "notes",
] as const;

export function assetImportTemplateCsv(): string {
  return rowsToCsv(ASSET_IMPORT_TEMPLATE_HEADERS, [
    [
      "Main",
      "Acme Property Management",
      "Tower A",
      "100 Market St",
      "San Francisco",
      "94105",
      "fire_extinguisher",
      "2nd floor · east stair",
      "FE-1042",
      "FE-1042",
      "Amerex",
      "",
      "",
      "2025-06-01",
      "2026-06-01",
      "",
    ],
    [
      "Main",
      "Acme Property Management",
      "Tower A",
      "100 Market St",
      "San Francisco",
      "94105",
      "fire_hydrant",
      "North parking lot",
      "HYD-01",
      "HYD-01",
      "",
      "",
      "",
      "2025-06-01",
      "",
      "Annual flow test",
    ],
    [
      "Main",
      "Acme Property Management",
      "Tower A",
      "100 Market St",
      "San Francisco",
      "94105",
      "standpipe",
      "Stair 2 · roof connection",
      "STP-A",
      "STP-A",
      "",
      "",
      "",
      "2025-06-01",
      "",
      "Annual inspection; 5-year flow tracked separately",
    ],
    [
      "Main",
      "Acme Property Management",
      "Tower A",
      "100 Market St",
      "San Francisco",
      "94105",
      "sprinkler_component",
      "Riser room B",
      "RISER-B",
      "RISER-B",
      "",
      "",
      "",
      "2026-03-01",
      "",
      "Quarterly riser check",
    ],
    [
      "Main",
      "Acme Property Management",
      "Tower A",
      "100 Market St",
      "San Francisco",
      "94105",
      "fire_alarm_panel",
      "Main lobby",
      "PANEL-1",
      "PANEL-1",
      "",
      "",
      "",
      "",
      "",
      "FACP",
    ],
  ]);
}
