ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "emailedTo" TEXT;
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "emailedAt" TIMESTAMP(3);
ALTER TABLE "reports" ADD COLUMN IF NOT EXISTS "emailError" TEXT;
